### ISSUE TITLE
Hola Pereira, Saluden!

### ISSUE THREAD

**Issue by cronopio** [nodeschool/pereira#4]
Aqui saludaremos desde Pereira.

**Comment by alsuga** [comment]
Hola!

**Comment by jhonier0571** [comment]
hola!!

**Comment by NoRoboto** [comment]
Hola!

**Comment by brymez1609** [comment]
Saludos!!

**Comment by al-lo-co** [comment]
Hola :D

**Comment by MrZero05** [comment]
Hello guys :)

**Comment by dialcg** [comment]
Tonces :dancer:

**Comment by jonalvarezz** [comment]
Hola a todos, que disfruten los workshops!

**Comment by lcorreat** [comment]
Hola

**Comment by Saulcoben** [comment]
Buenas

**Comment by sebasvega95** [comment]
Hello!!

**Comment by cronopio** [comment]
Gracias a todos por asistir!
Recuerden que pueden usar este repo para experimentar y para hacer preguntas en los Issues.
Sientanse con la confianza de usarlo.

Saludos y nos vemos en el próximo evento
