### ISSUE TITLE
Saludo NodeSchool Pereira

### ISSUE THREAD

**Issue by willyv78** [nodeschool/pereira#5]
Saludo de Wilson Velandia, Gracias

**Comment by jonalvarezz** [comment]
Saludo Wilson

**Comment by cronopio** [comment]
Hola @willyv78 Bienvenido!

Esperamos que disfrutes del evento!

**Comment by willyv78** [comment]
Gracias

**Comment by cronopio** [comment]
Gracias por haber asistido!
Para información  sobre futuras reuniones puede estar pendiente de la pagina: www.pereirajs.org
