### ISSUE TITLE
Buenas

### ISSUE THREAD

**Issue by Saulcoben** [nodeschool/pereira#6]
Buenos dias compañeros

**Comment by jonalvarezz** [comment]
Buen día!

**Comment by cronopio** [comment]
Hola @Saulcoben Bienvenenido!

Esperamos disfrutes del evento

**Comment by cronopio** [comment]
Gracias por haber asistido!
Para información sobre futuras reuniones puede estar pendiente de la pagina: www.pereirajs.org
