### ISSUE TITLE
Actualizar info para el evento de 2016.

### ISSUE THREAD

**Issue by pin3da** [nodeschool/pereira#9]

**Comment by jonalvarezz** [comment]
Confirmemos el lugar primero. @cronopio y yo hablábamos de hacerlo en la UCP, hubo buenas inscripciones, buena acogida y buen apoyo del director de Ingeniería de Sistemas. Lo hacemos ahí?

**Comment by cronopio** [comment]
@jonalvarezz Tratemos de contactarlo y preguntarle nuevamente sobre los computadores que dijo que prestaban y si les podemos instalar Node.js y poder correr los workshops

**Comment by pin3da** [comment]
Yo opino lo mismo. Allá está muy chévere el espacio, aguanta variar :P

**Comment by jonalvarezz** [comment]
Listo, ya empiezo la gestión

**Comment by jonalvarezz** [comment]
Confirmado el apoyo y disponibilidad en la UCP. Por el momento confirman disposición de al menos 20 equipos, habilitados para instalar node. La capacidad no me la confirman aún.

Hablan también de la posibilidad de realizar el evento entre semana para aprovechar y llevar los estudiantes en clases de programación. Aunque es claro que la fecha del 21 de mayo debe ser en ese día, es interesante para tenerlo en cuenta.

**Comment by jonalvarezz** [comment]
Update: sala con 26 equipos para 26 personas.

**Comment by jonalvarezz** [comment]
@pin3da @cronopio  👆

**Comment by pin3da** [comment]
Listo, de una!
